name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      KUBE_DEPLOYMENT: sample-deployment-c8f12d0c
      ECR_REPOSITORY: sample-app
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set Environment Variable
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo "IMAGE_REF=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV


    - name: build docker image
      run: docker build -t ${{ env.IMAGE_REF }} .
      working-directory: server

    - name: image push
      run: docker push ${{ env.IMAGE_REF }}

    - name: deploy to cluster
      uses: kodermax/kubectl-aws-eks@master
      with:
        args: set image deployment/$KUBE_DEPLOYMENT $ECR_REPOSITORY=${{ env.IMAGE_REF }}
        
    - name: verify deployment
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout status deployment/$KUBE_DEPLOYMENT